Update GitHub Actions workflow to print environment variables

diff --git a/.github/workflows/11-basics-expressions.yml b/.github/workflows/11-basics-expressions.yml
--- a/.github/workflows/11-basics-expressions.yml
+++ b/.github/workflows/11-basics-expressions.yml
@@ -12,11 +12,11 @@ jobs:
   print-hello-world:
     runs-on: ubuntu-latest
     steps:
-      - name: Print Hello World
-        # run: echo ${{ env.RUN_NUMBER }}
-        # run: echo ${{ env.TESTING_VALUE }}
-        run: exit 1
+      - name: NUMBER
+         run: echo ${{ env.RUN_NUMBER }}
+         
+        # run: exit 1
       
-      - name: Print Hello World 2
-        if: ${{ failure() }}
+      - name: TESTING
+        # if: ${{ failure() }}
         run: echo ${{ env.TESTING_VALUE }}
